### PR TITLE
Update snapshot URLs for test/data/repositories/ files if they exist

### PR DESCRIPTION
**Pull request by atodorov**

### CODE REVIEW

**Comment by atodorov** [comment]
FTR I've scheduled a manual snapshots update here: https://github.com/osbuild/rpmrepo/actions/runs/6009636554

**Comment by atodorov** [comment]
> FTR I've scheduled a manual snapshots update here: https://github.com/osbuild/rpmrepo/actions/runs/6009636554

The resulting PR is https://github.com/osbuild/osbuild-composer/pull/3664 which is missing the changes for `test/data/repositories/` b/c of a missing `git add`. Will update and schedule a new job.

**Comment by atodorov** [comment]
New job https://github.com/osbuild/rpmrepo/actions/runs/6011976318/job/16306430254, which should add test/data/repositories to the PR!

**Review by ondrejbudai — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
