### PR TITLE
Snapshot the EPEL repos

### PR DESCRIPTION
**Pull request by bcl**

### CODE REVIEW

**Review by dvdhrm — APPROVED** [review]
Are these "update" repositories? That is, do they change? Or are they immutable like the base repositories?

And do you know how the `epel/next/...` repoes relate to this?

Anyway, looks good regardless!

**Comment by bcl** [comment]
I still think this is a good idea, but apparently nobody else has hit the issue recently :)

**Comment by thozza** [comment]
> I still think this is a good idea, but apparently nobody else has hit the issue recently :)

So my suggestion would be to close this PR in case we do not have immediate need for EPEL snapshots. My reasoning is that we pay for the storage of snapshots. I don't dispute that this would be useful, I just think that we should do it now if we don't need it.

Some time ago, I reworked this repo in a way, so that the repo definitions are generated from https://github.com/osbuild/rpmrepo/blob/main/repo-definitions.yaml using `make snapshot-configs`. So it would be good to use that approach also for EPEL repos.

**Comment by bcl** [comment]
Closing for now. This was related to CI failures trying to update toml in the rhel 8.7.0 branch (https://github.com/osbuild/osbuild-composer/pull/3170), my suspicion was that it was due to mixing pinned and unpinned repos.

**Pull request closed without merging**
